
from pydantic import BaseModel, Field


class RAGRequest(BaseModel):
    query: str = Field(..., description="The query to be processed by the RAG system.")
  
class RAGResponse(BaseModel):
    request_id: str = Field(..., description="The request ID for tracking the RAG process.")
    answers: dict = Field(..., description="The answers generated by the RAG system.")